_target_: src.datamodules.DataModule
data_dir: ${data_dir}
batch_size: 256
num_workers: 10
prefetch_factor: 2
dataset: cifar100
do_active_learning: False
input_size: 224
n_examples_in_subset: null
vtab: False
vtab_complete: False
cross_val_index: null